apiVersion: updatebot.jenkins-x.io/v1alpha1
kind: UpdateConfig
spec:
  rules:
    - urls:
        - https://github.com/jx3-gitops-repositories/jx3-terraform-azure
      changes:
        - regex:
            pattern: "terraform-jx-azure\?ref=(.*)\""
            files:
              - "main.tf"
